[build]
  publish = "."
  command = "# no build command"

[functions]
  directory = "netlify/functions"

[dev]
  framework = "#custom"
  command = "node server.js"
  targetPort = 3001
  port = 8888
  functionsPort = 9999

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200